### ISSUE TITLE
Allow using <link> in customCSS

### ISSUE THREAD

**Issue by Kreyren** [hohMiyazawa/Automail#27] opened 2020-05-04 06:34 UTC
### Issue
I have the CustomCSS on https://github.com/Kreyren/anilist_css which requires copy+pasting to automail extension each time there is an update 

### Proposal
Allow alternative method of parsing the context by using `<link>` so that it can be sourced from https://github.com/Kreyren/anilist_css/blob/master/core.css

**Comment by hohMiyazawa** [comment] 2020-05-04 09:47
Will do some security research on that.

(be aware that your link is not a direct link to a stylesheet)

**Comment by Kreyren** [comment] 2020-05-04 19:01
> (be aware that your link is not a direct link to a stylesheet)

Elaborate?

**Comment by hohMiyazawa** [comment] 2020-05-04 19:04
If you want to serve css from Github, you have to use

https://raw.githubusercontent.com/Kreyren/anilist_css/master/core.css

**Comment by hohMiyazawa** [comment] 2020-05-07 11:52
Update: You can't even do that:
https://github.blog/2013-04-24-heads-up-nosniff-header-support-coming-to-chrome-and-firefox/

**Comment by hohMiyazawa** [comment] 2020-05-07 12:06
Current implementation (not live yet)

```javascript
if(jsonData.customCSS.match(/^https.*\.css$/)){
	let styleRef = document.createElement("link");
	styleRef.id = "customExternalCSS";
	styleRef.rel = "stylesheet";
	styleRef.type = "text/css";
	styleRef.href = jsonData.customCSS;
	document.getElementsByTagName("head")[0].appendChild(styleRef)
}
```

(plus a destructor)

**Comment by Kreyren** [comment] 2020-05-07 16:28
> Update: You can't even do that: https://github.blog/2013-04-24-heads-up-nosniff-header-support-coming-to-chrome-and-firefox/

Correct me if i am wrong, but it seems that using raw in repository pins the master version and is updated on each commit? https://raw.githubusercontent.com/Kreyren/anilist_css/master/core.css

So i assume that mensioned concerns apply to gists only?

(i just woke up though so i am more likely to say something stupid)

**Comment by hohMiyazawa** [comment] 2020-05-07 18:11
@Kreyren The issue is that it gets served as "text/plain" from Github, which means the browser will refuse to use it as a stylesheet:

https://i.stack.imgur.com/cZ6jw.png

**Comment by Kreyren** [comment] 2020-05-07 19:46
I see, what do you propose as a solution?

***kreyren** wants to avoid making CD workflow*

**Comment by Kreyren** [comment] 2020-05-07 19:52
Aldo checking the file:
```console
kreyren@leonid:~$ file /tmp/kaniliast.css 
/tmp/kaniliast.css: assembler source, ASCII text
```

I don't see anything that would cause this issue -> Maybe it's getting confused by me using `@-moz-document` or something?

**Comment by hohMiyazawa** [comment] 2020-05-07 21:38
It's a header, it has nothing to do with the contents of your file.

You just need to serve it from somewhere that doesn't add the "X-Content-Type-Options: nosniff" header, because browsers respect that.

**Comment by hohMiyazawa** [comment] 2020-05-07 21:41
But anyway, the proposal is implemented. Closing this.

**Closed by hohMiyazawa** 2020-05-07 21:41 UTC
Labels: feature-request

**Comment by Kreyren** [comment] 2020-05-07 21:45
thanks for working on this ^-^

**Comment by aushamim** [comment] 2024-06-27 17:59
Hey, although direct linking a CSS file from github as a link does not work I think a workaround can be implemented.
I have tested this in a JS file and it seems to work. Don't know if it will work with automail. But please check if this can be implemented.

```JS
  const url = "https://raw.githubusercontent.com/some-user/some-repo/some-branch/some/path/file.css";
  const urlPattern = /^https:\/\/raw\.githubusercontent\.com\/.*\.css$/;

  if (urlPattern.test(url)) {
    fetch(url)
      .then((res) => res.text())
      .then((data) => {
        let styleRef = document.createElement("style");
        styleRef.id = "customExternalCSS";
        styleRef.innerHTML = data;
        document.getElementsByTagName("head")[0].appendChild(styleRef);
      });
  }
```

Here it checks if the link is from `https://raw.githubusercontent.com/` and if the link ends with `.css`. Then using fetch function to load the data and rest is basically the same.

**Comment by hohMiyazawa** [comment] 2024-06-27 18:04
@aushamim I'm rather hesitant to implement additional ways of loading external content, and at least I would have someone more knowledgeable than me look it over first.

But AFAIK, just hosting it somewhere that serves it with the correct headers should still work today.

**Comment by aushamim** [comment] 2024-06-27 18:17
@hohMiyazawa Yes, hosting elsewhere works. But for me and other users who upload their CSS to GitHub, reducing another step to update to external hosting would be great.
